# Generated by Django 4.2.6 on 2023-10-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('publisheddate', models.PositiveIntegerField()),
            ],
        ),
    ]
