# Generated by Django 4.2.6 on 2023-11-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_booksapp_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksapp',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
